### ISSUE TITLE
[Failure] PDO exception when opening paperwork grain created with earlier version

### ISSUE THREAD

**Issue by erikmaarten** [JamborJan/paperwork#28] opened 2015-09-01 17:42 UTC
I upgraded Paperwork to the version from the app store yesterday, and now I can't open Paperwork grains created with the previous version I was using (don't know if it had a version number).

Yesterday I just got a blank page when trying to open old Paperwork grains, but today I get an exception. I changed my "Full Name" in the Sandstorm account settings, but it seems odd if an application uses that for something critical.

Here's the trace log:

```
30. PDOException
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Connectors/­Connector.php47
29. PDO __construct
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Connectors/­Connector.php47
28. Illuminate\Database\Connectors\Connector createConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Connectors/­MySqlConnector.php20
27. Illuminate\Database\Connectors\MySqlConnector connect
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Connectors/­ConnectionFactory.php57
26. Illuminate\Database\Connectors\ConnectionFactory createSingleConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Connectors/­ConnectionFactory.php46
25. Illuminate\Database\Connectors\ConnectionFactory make
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­DatabaseManager.php176
24. Illuminate\Database\DatabaseManager makeConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­DatabaseManager.php64
23. Illuminate\Database\DatabaseManager connection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php2922
22. Illuminate\Database\Eloquent\Model resolveConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php2888
21. Illuminate\Database\Eloquent\Model getConnection
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1849
20. Illuminate\Database\Eloquent\Model newBaseQueryBuilder
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1790
19. Illuminate\Database\Eloquent\Model newQueryWithoutScopes
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php1764
18. Illuminate\Database\Eloquent\Model newQuery
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Model.php640
17. Illuminate\Database\Eloquent\Model all
…/­app/­controllers/­UserController.php127
16. UserController showLoginForm
<#unknown>0
15. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Controller.php231
14. Illuminate\Routing\Controller callAction
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php93
13. Illuminate\Routing\ControllerDispatcher call
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php62
12. Illuminate\Routing\ControllerDispatcher dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php967
11. Illuminate\Routing\Router Illuminate\Routing\{closure}
<#unknown>0
10. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Route.php109
9. Illuminate\Routing\Route run
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1033
8. Illuminate\Routing\Router dispatchToRoute
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1001
7. Illuminate\Routing\Router dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php775
6. Illuminate\Foundation\Application dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php745
5. Illuminate\Foundation\Application handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Session/­Middleware.php72
4. Illuminate\Session\Middleware handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Queue.php47
3. Illuminate\Cookie\Queue handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Guard.php51
2. Illuminate\Cookie\Guard handle
…/­vendor/­stack/­builder/­src/­Stack/­StackedHttpKernel.php23
1. Stack\StackedHttpKernel handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php641
0. Illuminate\Foundation\Application run
…/­public/­index.php49
```

The error page also showed some request info:

```
Server/Request Data
FCGI_ROLE 	RESPONDER
QUERY_STRING 	
REQUEST_METHOD 	GET
CONTENT_TYPE 	
CONTENT_LENGTH 	
SCRIPT_FILENAME 	/opt/app/frontend/public/index.php
SCRIPT_NAME 	/index.php
REQUEST_URI 	/login
DOCUMENT_URI 	/index.php
DOCUMENT_ROOT 	/opt/app/frontend/public
SERVER_PROTOCOL 	HTTP/1.1
GATEWAY_INTERFACE 	CGI/1.1
SERVER_SOFTWARE 	nginx/1.4.6
REMOTE_ADDR 	127.0.0.1
REMOTE_PORT 	33329
SERVER_ADDR 	127.0.0.1
SERVER_PORT 	33411
SERVER_NAME 	
REDIRECT_STATUS 	200
HTTP_CONNECTION 	close
HTTP_ACCEPT_ENCODING 	gzip
HTTP_ACCEPT_LANGUAGE 	en-US,en;q=0.5
HTTP_USER_AGENT 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0
HTTP_X_SANDSTORM_USERNAME 	[redacted]
HTTP_X_SANDSTORM_USER_ID 	[redacted]
HTTP_X_SANDSTORM_PERMISSIONS 	admin
HTTP_X_SANDSTORM_BASE_PATH 	https://[redacted].oasis.sandstorm.io
HTTP_HOST 	[redacted].oasis.sandstorm.io
HTTP_X_FORWARDED_PROTO 	https
HTTP_X_SANDSTORM_SESSION_ID 	0
HTTP_COOKIE 	[redacted]
HTTP_ACCEPT 	text/html, application/xhtml+xml, application/xml; q=0.9, */*; q=0.8
PHP_SELF 	/index.php
REQUEST_TIME_FLOAT 	1441128245.4376
REQUEST_TIME 	1441128245
HTTPS 	on
GET Data
empty
POST Data
empty
Files
empty

Session
empty
Environment Variables
empty
Registered Handlers
```

**Comment by JamborJan** [comment] 2015-09-01 18:10
Hey @erikmaarten,

There was unfortunately an issue with the database caused by some trouble in the upstream repo. Details can be found here: 
- https://groups.google.com/forum/#!searchin/sandstorm-dev/paperwork/sandstorm-dev/ObdnUs2vyrU/HHNXVRf84Q0J
- https://github.com/JamborJan/paperwork/issues/13

This should only happen when upgrading from the very first version of the app. I changed the app ID to prevent such issues like described by you.

To track down the issue I would like to ask you the following: install this version of the app: https://github.com/JamborJan/paperwork/releases/tag/V4. Proceed like described in the release notes:

- Backup your data
- Install V4 of the app
- Start an old instance
- An export page is shown
- Click the export button
- Save the ENEX XML file on your local hard drive
- Close this instance
- Install the latest version of the app via Sandstorm app store when not already done (both versions can be installed parallel)
- Create a new empty instance with the new app
- In Paperwork go to Settings - Import/Export and import your data again
- Now you have a fresh version of your grain with all your data.

Can you please check that?

What happens if you create an empty new grain?

Thanks a lot for your help and patience.

JJ

**Comment by erikmaarten** [comment] 2015-09-01 18:53
Haven't gotten around to try the steps, will do that next, but I've tried creating a new grain. With the new version, a grain is created without problem, with that old version I used previously I got an error the first time (see below) but subsequently it just opens a new grain without problems (seemingly using the old version of Paperwork, if that can be judged by the absence of the calendar in the left sidebar).

```
Error: remote exception: remote exception: remote exception: remote exception: remote exception: remote exception: connect(): Connection refused
C++ location:(remote):??
type: disconnected
```

**Comment by JamborJan** [comment] 2015-09-01 19:09
Yeah unfortunately there is no easy way to detect the version at the moment. In the old UI of sandstorm the version was displayed beside the app name. Thats gone now. But in that case the calendar is a good indication. 

I will wait for your feedback. Hopefully we can solve the issue and you can continue to use the app with all your data.

Anyway I'm here to help.

JJ

**Comment by erikmaarten** [comment] 2015-09-01 20:13
Have gone through all the steps for my Paperwork grains now, 7 out of 8 were fine to export and import. The one that didn't work didn't really give any indication as to why, just a message inside Paperwork saying the import failed. I just had two notes in it anyway, so it's not a big deal, and at the very least I guess I can just copy and paste the html for each note from the enex file (at least it looks like that should be fine).

Apart from that there was only one minor problem -- the original notebooks weren't recreated, all notes just ended up in a new Evernote[someDate] notebook. Not a big deal though, my biggest notebook had less than 20 notes anyway.

Thanks for helping!

**Comment by erikmaarten** [comment] 2015-09-01 20:21
Another slight problem/bug I found just now: Notes can't be moved to the folder automatically created (the Evernote... folder) when importing.

**Comment by JamborJan** [comment] 2015-09-02 04:30
Hi @erikmaarten,

I'm glad it worked. Here some additional answers to your 3 questions:

The one note not being imported is most likely related to special characters in the title. See: https://github.com/JamborJan/paperwork/issues/27. I'm currently working on that together with the maintainers of the upstream repository. A work around is to open an ENEX file and replace especially `&nbsp;`by normal spaces.

The ENEX xml structure unfortunately doesn't support notebooks. So also when you use the file in Evernote it will not create the notebooks. Thats why there will be a new Notebook with date and time in the name.

I'm not quite sure if I got your last comment right about the automatically crated notebook. Do you mean during the process of import or in general it is not possible to move notes into this notebook? If you are able to describe this in a new issue I will take a look in detail

Thanks again for contributing, I'll close this issue as the main problem is solved. If you have any other questions let me know.

JJ

**Closed by JamborJan** 2015-09-02 04:30 UTC
Labels: bug
